# Generated by Django 5.2.7 on 2025-10-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_nota_curso_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido_estduiante',
            new_name='apellido_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='edad_estdudiante',
            new_name='edad_estudiante',
        ),
    ]
